name: Playground

#on: push
on:
  schedule:
    - cron: '30 12 14-15 * 2' # At 09:30 am on every day-of-month from 14 through 15 and on Tuesday. (JST)
  workflow_dispatch:

jobs:
  date:
    name: Run date command
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-output name=today::$(LANG=C date '+%A')"
        id: day-of-week
    outputs:
      day-of-week: ${{ steps.day-of-week.outputs.today }}

  run-only-tuesday:
    name: Run only Tuesday
    runs-on: ubuntu-latest
    needs: date
    #  直前の "date" Job で outputs を使って date コマンドの結果を保持し、
    # 実行したい Tuesday である場合のみ Job を実行
    if: needs.date.outputs.day-of-week == 'Tuesday'
    steps:
      - name: echo day-of-week
        run: echo ${{ needs.date.outputs.day-of-week }}
      # Job レベルで実行制御しているので複数のstepをまとめて実行するかしないか決めている
      - name: echo hoge
        run: echo "hoge"


