name: Playground

#on: push
on:
  workflow_dispatch:

jobs:
  date:
    name: Run date command
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-output name=today::$(LANG=C date '+%A')"
        id: day-of-week
    outputs:
      day-of-week: ${{ steps.day-of-week.outputs.today }}

  # Run only Monday
  run-only-monday:
    name: Playground Job
    runs-on: ubuntu-latest
    needs: date
    #  直前の "date" Job で outputs を使って date コマンドの結果を保持し、実行したい Monday (月曜日)である場合のみ "run-only-monday" Job を実行
    if: needs.date.outputs.day-of-week == 'Monday'
    steps:
      - name: echo day-of-week
        run: echo ${{ needs.date.outputs.day-of-week }}
      # Job レベルで実行制御しているので複数のstepをまとめて実行するかしないか決めている
      - name: echo hoge
        run: echo "hoge"


