name: Playground

#on: push
on:
  workflow_dispatch:

jobs:
  check-if-today-is-monday:
    name: Check if today is Monday
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-output name=today::$(LANG=C date '+%A')"
        id: day-of-week
    outputs:
      day-of-week: ${{ steps.day-of-week.outputs.today }}

  # Run only Monday
  run-only-monday:
    name: Playground Job
    runs-on: ubuntu-latest
    needs: check-if-today-is-monday
    if: success()
    steps:
      - name: echo day-of-week
        run: echo ${{ needs.date.outputs.day-of-week }}


