name: Playground

#on: push
on:
  schedule:
    - cron: '00 5 16-17 * 4' # At 02:00 pm on every day-of-month from 16 through 17 and on Thursday. (JST)
  workflow_dispatch:

jobs:
  date:
    name: Run date command
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-output name=today::$(LANG=C date '+%A')"
        id: day-of-week
    outputs:
      day-of-week: ${{ steps.day-of-week.outputs.today }}

  echo:
    name: echo
    runs-on: ubuntu-latest
    needs: date
    #  直前の "date" Job で outputs を使って date コマンドの結果を保持し、
    # 実行したい 曜日 である場合のみ Job を実行
    if: needs.date.outputs.day-of-week == 'Thursday'
    steps:
      - name: echo day-of-week
        run: echo ${{ needs.date.outputs.day-of-week }}
      # Job レベルで実行制御しているので複数のstepをまとめて実行するかしないか決めている
      - name: echo hoge
        run: echo "hoge"


