name: Playground

#on: push
on:
  schedule:
    - cron: 55 9 10-11 * *  # At 06:55 pm on every day-of-month from 10 through 11.(JST) 
  workflow_dispatch:

jobs:
  check-if-today-is-monday:
    name: Check if today is Monday
    runs-on: ubuntu-latest
    steps:
      - run: if [ $(date +%u) -eq 1 ]; then exit 0; fi

  # Run only Monday 
  playground:
    name: Playground Job
    runs-on: ubuntu-latest
    needs: check-if-today-is-monday
    steps:
      - name: Hello, world!
        run: |
          echo "Hello, world!"
