name: Playground

#on: push
on:
  schedule:
    - cron: 20 9 10-11 * *
  workflow_dispatch:

jobs:
  check-if-today-is-monday:
    name: check if today is Monday
    runs-on: ubuntu-latest
    steps:
      - run: if [ $(date +%u) -eq 4 ]; then exit 0; fi
  playground: # Run only Monday
    needs: check-if-today-is-monday
    name: Playground Job
    runs-on: ubuntu-latest
    steps:
      - name: Hello, world!
        run: |
          echo "Hello, world!"
