name: Playground

on:
  workflow_dispatch:

jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - name: Generate 0 or 1
        id: generate_number
        run:  echo "::set-output name=random_number::$(($RANDOM % 2))"
      - name: Pass or fail # 不安定な Step
        id: generate_number_outputs
        continue-on-error: true
        run: >
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]];
          then exit 0; else exit 1; fi
      - name: "steps.generate_number_outputs.outcome の値確認"
        run: echo "${{ steps.generate_number_outputs.outcome }}"
      - name: "steps.generate_number_outputs.conclusion の値確認"
        run: echo "${{ steps.generate_number_outputs.conclusion }}"
      - name: "success のときだけ"
        if: ${{ steps.generate_number_outputs.outcome == 'success' }}
        run: echo "OK"
      - name: "failure のときだけ"
        if: ${{ steps.generate_number_outputs.outcome == 'failure' }}
        run:  echo "Failed"
