name: Playground

on:
  workflow_dispatch:

jobs:
  simele-job:
    runs-on: ubuntu-latest
    steps:
      - name: Datadog Agent
        uses: DataDog/agent-github-action@v1
        with:
          api_key: ${{ secrets.DD_API_KEY }}
      - run: npm ci
      - run: make test
