name: Playground

on:
  workflow_dispatch:

#permissions:
#  contents: write
#  pull-requests: write

jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    outputs:
      random-number-output: ${{ steps.generate_number.outputs.random_number }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate 0 or 1
        id: generate_number
        run:  echo "::set-output name=random_number::$(($RANDOM % 2))"
      - name: Pass or fail # 不安定な Step
        id: generate_number_outputs
        run: |
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then
          exit 0; else exit 1; fi

      - run: echo "Alice"
        if: always()
      - run: echo "Bob"
      - run: echo "Charlie"

  random-number-output:
    runs-on: ubuntu-latest
    needs: randomly-failing-job
    #permissions:
    #  contents: write
    #  pull-requests: write
    steps:
      - run: echo ${{ needs.randomly-failing-job.outputs.random-number-output }}

