name: Playground

on:
  workflow_dispatch:

jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - name: Generate 0 or 1
        id: generate_number
        run:  echo "::set-output name=random_number::$(($RANDOM % 2))"
      - run: echo "OK"
        if: ${{ steps.generate_number.outputs.random_number == 0 }}
      - run: echo "Failed"
        if: ${{ steps.generate_number.outputs.random_number == 1 }}
