name: Workflow as entrypoint (workflow_dispatch)
'on':
  push:
    branches:
      - main

jobs:
  main:
    runs-on: 'ubuntu-20.04'
    env:
      REPOSITORY_DISPATCH_EVENT_TYPE: 'release-stg'
      APP_REPOSITORY_URL: 'https://github.com/gkzz/actions-playground'

    steps:
      - uses: actions/checkout@v2

      - name: Set app rpeository workflow url
        #run: echo -n "${{ env.APP_REPOSITORY_URL }}/actions/runs/${GITHUB_RUN_ID}" > /tmp/.appwf.txt
        run: echo "${{ env.APP_REPOSITORY_URL }}/actions/runs/${GITHUB_RUN_ID}" > /tmp/.appwf.txt

      - name: Read appwf.txt
        # https://github.com/marketplace/actions/read-file
        id: read-appwf
        uses: juliangruber/read-file-action@v1
        with:
          path: /tmp/.appwf.txt

      - name: Workflow Dispatch
        # https://github.com/benc-uk/workflow-dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Subsequent workflow (workflow_dispatch)
          #token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.ACTIONS_PLAYGROUND_WORKFLOW_DISPATCH }} # Both public and private
          repo: 'gkzz/actions-dispatch-playground'
          #ref: 'main'
          ref: 'work'
          inputs: '{
            "github_sha": "${{ github.sha }}",
            "appwf_url": "${{ steps.read-appwf.outputs.content }}"}'

      # https://docs.github.com/ja/rest/reference/actions#create-a-workflow-dispatch-event
      # https://zenn.dev/masaaania/articles/c930f2f755a577
      #- name: Workflow Dispatch with curl command
      #  run: |
      #    curl -X POST \
      #    -H "Accespt: application/vnd.github.v3+json" \
      #    -H "Authorization: token ${{ secrets.ACTIONS_PLAYGROUND_WORKFLOW_DISPATCH }}" \
      #    https://api.github.com/repos/gkzz/actions-dispatch-playground/actions/workflows/wf_dispatch_release.yml/dispatches \
      #    -d '{"ref":"main", "inputs":{"github_sha": "${{ github.sha }}", "appwf_url": "${{ steps.read-appwf.outputs.content }}"}}'
